spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: piggymetrics
      port: 27017

server:
  context-path: /uaa
  port: 5000
  
logging:
  level:
    org.springframework.security: DEBUG


    #add for Spring Boot 1.5.3+ Dalston.RELEASE
security:
  oauth2:
    resource:
    filter-order : 3